import QtQuick

import MMaterial.Media as Media

QtObject {
	id: root

	property Media.IconData priorityHigh
	property Media.IconData pause
	property Media.IconData logo
	property Media.IconData accountBalance
	property Media.IconData accountBox
	property Media.IconData accountCircle
	property Media.IconData adb
	property Media.IconData add
	property Media.IconData addAPhoto
	property Media.IconData addBox
	property Media.IconData addBusiness
	property Media.IconData addCard
	property Media.IconData addCircle
	property Media.IconData addPhotoAlternate
	property Media.IconData addShoppingCart
	property Media.IconData air
	property Media.IconData alarm
	property Media.IconData analytics
	property Media.IconData android
	property Media.IconData apps
	property Media.IconData arrowBack
	property Media.IconData arrowDownward
	property Media.IconData arrowDropDown
	property Media.IconData arrowDropUp
	property Media.IconData arrowForward
	property Media.IconData arrowRight
	property Media.IconData atr
	property Media.IconData attachMoney
	property Media.IconData autorenew
	property Media.IconData backspace
	property Media.IconData badge
	property Media.IconData barChart
	property Media.IconData barcodeScanner
	property Media.IconData batteryChargingFull
	property Media.IconData batteryFull
	property Media.IconData batteryFullAlt
	property Media.IconData bluetooth
	property Media.IconData bookmark
	property Media.IconData brush
	property Media.IconData build
	property Media.IconData cable
	property Media.IconData cake
	property Media.IconData calculate
	property Media.IconData calendarMonth
	property Media.IconData calendarToday
	property Media.IconData call
	property Media.IconData camera
	property Media.IconData campaign
	property Media.IconData cancel
	property Media.IconData cast
	property Media.IconData category
	property Media.IconData celebration
	property Media.IconData chat
	property Media.IconData chatBubble
	property Media.IconData check
	property Media.IconData checkBox
	property Media.IconData checkBoxOutlineBlank
	property Media.IconData checkCircle
	property Media.IconData chevronLeft
	property Media.IconData chevronRight
	property Media.IconData circle
	property Media.IconData close
	property Media.IconData code
	property Media.IconData computer
	property Media.IconData construction
	property Media.IconData contactSupport
	property Media.IconData contentCopy
	property Media.IconData creditCard
	property Media.IconData cropFree
	property Media.IconData currencyBitcoin
	property Media.IconData darkMode
	property Media.IconData dashboard
	property Media.IconData database
	property Media.IconData deleteElement
	property Media.IconData deleteForever
	property Media.IconData description
	property Media.IconData devices
	property Media.IconData directionsCar
	property Media.IconData domain
	property Media.IconData doneAll
	property Media.IconData download
	property Media.IconData downloadForOffline
	property Media.IconData draw
	property Media.IconData eco
	property Media.IconData edit
	property Media.IconData editNote
	property Media.IconData electricBolt
	property Media.IconData emojiObjects
	property Media.IconData engineering
	property Media.IconData error
	property Media.IconData euro
	property Media.IconData event
	property Media.IconData explore
	property Media.IconData extension
	property Media.IconData familiarFaceAndZone
	property Media.IconData fastForward
	property Media.IconData fastRewind
	property Media.IconData favorite
	property Media.IconData fileCopy
	property Media.IconData filterAlt
	property Media.IconData filterList
	property Media.IconData finance
	property Media.IconData fingerprint
	property Media.IconData flag
	property Media.IconData flashOn
	property Media.IconData flashlightOn
	property Media.IconData flight
	property Media.IconData folder
	property Media.IconData folderOpen
	property Media.IconData forum
	property Media.IconData gridOn
	property Media.IconData gridView
	property Media.IconData group
	property Media.IconData groupAdd
	property Media.IconData groups
	property Media.IconData handyman
	property Media.IconData headphones
	property Media.IconData hearing
	property Media.IconData help
	property Media.IconData history
	property Media.IconData home
	property Media.IconData homePin
	property Media.IconData image
	property Media.IconData imagesmode
	property Media.IconData info
	property Media.IconData inventory
	property Media.IconData inventory2
	property Media.IconData keyboardArrowDown
	property Media.IconData keyboardArrowLeft
	property Media.IconData keyboardArrowRight
	property Media.IconData keyboardArrowUp
	property Media.IconData label
	property Media.IconData landscape
	property Media.IconData language
	property Media.IconData leaderboard
	property Media.IconData lightMode
	property Media.IconData lightbulb
	property Media.IconData link
	property Media.IconData list
	property Media.IconData localCafe
	property Media.IconData localMall
	property Media.IconData locationOn
	property Media.IconData lock
	property Media.IconData lockOpen
	property Media.IconData login
	property Media.IconData logout
	property Media.IconData loyalty
	property Media.IconData mail
	property Media.IconData manageAccounts
	property Media.IconData map
	property Media.IconData menu
	property Media.IconData mic
	property Media.IconData modeComment
	property Media.IconData monitoring
	property Media.IconData moreHoriz
	property Media.IconData moreVert
	property Media.IconData movie
	property Media.IconData musicNote
	property Media.IconData myLocation
	property Media.IconData navigation
	property Media.IconData nearMe
	property Media.IconData nestEcoLeaf
	property Media.IconData nestRemoteComfortSensor
	property Media.IconData nightlight
	property Media.IconData notifications
	property Media.IconData openInNew
	property Media.IconData paid
	property Media.IconData palette
	property Media.IconData pauseCircle
	property Media.IconData person
	property Media.IconData personAdd
	property Media.IconData personPin
	property Media.IconData pets
	property Media.IconData phoneIphone
	property Media.IconData photoCamera
	property Media.IconData photoLibrary
	property Media.IconData pictureAsPdf
	property Media.IconData pinDrop
	property Media.IconData playArrow
	property Media.IconData playCircle
	property Media.IconData power
	property Media.IconData printElement
	property Media.IconData publicElement
	property Media.IconData qrCode
	property Media.IconData qrCode2
	property Media.IconData qrCodeScanner
	property Media.IconData queryStats
	property Media.IconData questionMark
	property Media.IconData radar
	property Media.IconData refresh
	property Media.IconData remove
	property Media.IconData repeat
	property Media.IconData replay
	property Media.IconData report
	property Media.IconData restartAlt
	property Media.IconData restaurant
	property Media.IconData restaurantMenu
	property Media.IconData rocketLaunch
	property Media.IconData rssFeed
	property Media.IconData save
	property Media.IconData savings
	property Media.IconData schedule
	property Media.IconData school
	property Media.IconData science
	property Media.IconData search
	property Media.IconData security
	property Media.IconData sell
	property Media.IconData send
	property Media.IconData settings
	property Media.IconData share
	property Media.IconData shoppingBag
	property Media.IconData shoppingCart
	property Media.IconData shuffle
	property Media.IconData signalCellularAlt
	property Media.IconData skipNext
	property Media.IconData skipPrevious
	property Media.IconData smartphone
	property Media.IconData sort
	property Media.IconData sportsEsports
	property Media.IconData sportsSoccer
	property Media.IconData stadiaController
	property Media.IconData star
	property Media.IconData stop
	property Media.IconData stopCircle
	property Media.IconData storage
	property Media.IconData store
	property Media.IconData storefront
	property Media.IconData subscriptions
	property Media.IconData sync
	property Media.IconData taskAlt
	property Media.IconData theaters
	property Media.IconData thumbUp
	property Media.IconData timeline
	property Media.IconData timer
	property Media.IconData touchApp
	property Media.IconData trendingDown
	property Media.IconData trendingUp
	property Media.IconData tune
	property Media.IconData undo
	property Media.IconData update
	property Media.IconData uploadFile
	property Media.IconData usb
	property Media.IconData verified
	property Media.IconData verifiedUser
	property Media.IconData videoLibrary
	property Media.IconData videocam
	property Media.IconData visibility
	property Media.IconData visibilityOff
	property Media.IconData volumeOff
	property Media.IconData volumeUp
	property Media.IconData wallet
	property Media.IconData wallpaper
	property Media.IconData warning
	property Media.IconData wbSunny
	property Media.IconData whereToVote
	property Media.IconData widgets
	property Media.IconData wifi
	property Media.IconData wifiOff
	property Media.IconData work
	property Media.IconData dashedCircle
	property Media.IconData colorize


    function getAll() : list<string> {
		return root.getPropertyNames(this);
    }

	function getPropertyNames(iconContainer: QtObject) : list<string> {
		let names = [];
		for (var key in iconContainer) {
			if (iconContainer.hasOwnProperty(key) && typeof iconContainer[key] == "object") {
				names.push(key);
			}
		}
		return names;
	}
}
