pragma Singleton

import QtQuick

import MMaterial.Media as Media

QtObject{
    id: _root

	readonly property Media.IconSet light: Media.IconSet {
		// inventory2: Media.IconData { path: '\ue900'; type: Media.IconData.Light }
		// keyboardArrowDown: Media.IconData { path: '\ue901'; type: Media.IconData.Light }
		// keyboardArrowLeft: Media.IconData { path: '\ue902'; type: Media.IconData.Light }
		// keyboardArrowRight: Media.IconData { path: '\ue903'; type: Media.IconData.Light }
		// keyboardArrowUp: Media.IconData { path: '\ue904'; type: Media.IconData.Light }
		// label: Media.IconData { path: '\ue905'; type: Media.IconData.Light }
		// landscape: Media.IconData { path: '\ue906'; type: Media.IconData.Light }
		// language: Media.IconData { path: '\ue907'; type: Media.IconData.Light }
		// leaderboard: Media.IconData { path: '\ue908'; type: Media.IconData.Light }
		// lightMode: Media.IconData { path: '\ue909'; type: Media.IconData.Light }
		// lightbulb: Media.IconData { path: '\ue90a'; type: Media.IconData.Light }
		// link: Media.IconData { path: '\ue90b'; type: Media.IconData.Light }
		// list: Media.IconData { path: '\ue90c'; type: Media.IconData.Light }
		// localCafe: Media.IconData { path: '\ue90d'; type: Media.IconData.Light }
		// localMall: Media.IconData { path: '\ue90e'; type: Media.IconData.Light }
		// locationOn: Media.IconData { path: '\ue90f'; type: Media.IconData.Light }
		// lock: Media.IconData { path: '\ue910'; type: Media.IconData.Light }
		// lockOpen: Media.IconData { path: '\ue911'; type: Media.IconData.Light }
		// login: Media.IconData { path: '\ue912'; type: Media.IconData.Light }
		// logout: Media.IconData { path: '\ue913'; type: Media.IconData.Light }
		// loyalty: Media.IconData { path: '\ue914'; type: Media.IconData.Light }
		// mail: Media.IconData { path: '\ue915'; type: Media.IconData.Light }
		// manageAccounts: Media.IconData { path: '\ue916'; type: Media.IconData.Light }
		// map: Media.IconData { path: '\ue917'; type: Media.IconData.Light }
		// menu: Media.IconData { path: '\ue918'; type: Media.IconData.Light }
		// mic: Media.IconData { path: '\ue919'; type: Media.IconData.Light }
		// modeComment: Media.IconData { path: '\ue91a'; type: Media.IconData.Light }
		// monitoring: Media.IconData { path: '\ue91b'; type: Media.IconData.Light }
		// moreHoriz: Media.IconData { path: '\ue91c'; type: Media.IconData.Light }
		// moreVert: Media.IconData { path: '\ue91d'; type: Media.IconData.Light }
		// movie: Media.IconData { path: '\ue91e'; type: Media.IconData.Light }
		// musicNote: Media.IconData { path: '\ue91f'; type: Media.IconData.Light }
		// myLocation: Media.IconData { path: '\ue920'; type: Media.IconData.Light }
		// navigation: Media.IconData { path: '\ue921'; type: Media.IconData.Light }
		// nearMe: Media.IconData { path: '\ue922'; type: Media.IconData.Light }
		// nestEcoLeaf: Media.IconData { path: '\ue923'; type: Media.IconData.Light }
		// nestRemoteComfortSensor: Media.IconData { path: '\ue924'; type: Media.IconData.Light }
		// nightlight: Media.IconData { path: '\ue925'; type: Media.IconData.Light }
		// notifications: Media.IconData { path: '\ue926'; type: Media.IconData.Light }
		// openInNew: Media.IconData { path: '\ue927'; type: Media.IconData.Light }
		// paid: Media.IconData { path: '\ue928'; type: Media.IconData.Light }
		// palette: Media.IconData { path: '\ue929'; type: Media.IconData.Light }
		// pause: Media.IconData { path: '\ue92a'; type: Media.IconData.Light }
		// pauseCircle: Media.IconData { path: '\ue92b'; type: Media.IconData.Light }
		// person: Media.IconData { path: '\ue92c'; type: Media.IconData.Light }
		// personAdd: Media.IconData { path: '\ue92d'; type: Media.IconData.Light }
		// personPin: Media.IconData { path: '\ue92e'; type: Media.IconData.Light }
		// pets: Media.IconData { path: '\ue92f'; type: Media.IconData.Light }
		// phoneIphone: Media.IconData { path: '\ue930'; type: Media.IconData.Light }
		// photoCamera: Media.IconData { path: '\ue931'; type: Media.IconData.Light }
		// photoLibrary: Media.IconData { path: '\ue932'; type: Media.IconData.Light }
		// pictureAsPdf: Media.IconData { path: '\ue933'; type: Media.IconData.Light }
		// pinDrop: Media.IconData { path: '\ue934'; type: Media.IconData.Light }
		// playArrow: Media.IconData { path: '\ue935'; type: Media.IconData.Light }
		// playCircle: Media.IconData { path: '\ue936'; type: Media.IconData.Light }
		// power: Media.IconData { path: '\ue937'; type: Media.IconData.Light }
		// printElement: Media.IconData { path: '\ue938'; type: Media.IconData.Light }
		// priorityHigh: Media.IconData { path: '\ue939'; type: Media.IconData.Light }
		// publicElement: Media.IconData { path: '\ue93a'; type: Media.IconData.Light }
		// qrCode: Media.IconData { path: '\ue93b'; type: Media.IconData.Light }
		// qrCode2: Media.IconData { path: '\ue93c'; type: Media.IconData.Light }
		// qrCodeScanner: Media.IconData { path: '\ue93d'; type: Media.IconData.Light }
		// queryStats: Media.IconData { path: '\ue93e'; type: Media.IconData.Light }
		// questionMark: Media.IconData { path: '\ue93f'; type: Media.IconData.Light }
		// radar: Media.IconData { path: '\ue940'; type: Media.IconData.Light }
		// refresh: Media.IconData { path: '\ue941'; type: Media.IconData.Light }
		// remove: Media.IconData { path: '\ue942'; type: Media.IconData.Light }
		// repeat: Media.IconData { path: '\ue943'; type: Media.IconData.Light }
		// replay: Media.IconData { path: '\ue944'; type: Media.IconData.Light }
		// report: Media.IconData { path: '\ue945'; type: Media.IconData.Light }
		// restartAlt: Media.IconData { path: '\ue946'; type: Media.IconData.Light }
		// restaurant: Media.IconData { path: '\ue947'; type: Media.IconData.Light }
		// restaurantMenu: Media.IconData { path: '\ue948'; type: Media.IconData.Light }
		// rocketLaunch: Media.IconData { path: '\ue949'; type: Media.IconData.Light }
		// rssFeed: Media.IconData { path: '\ue94a'; type: Media.IconData.Light }
		// save: Media.IconData { path: '\ue94b'; type: Media.IconData.Light }
		// savings: Media.IconData { path: '\ue94c'; type: Media.IconData.Light }
		// schedule: Media.IconData { path: '\ue94d'; type: Media.IconData.Light }
		// school: Media.IconData { path: '\ue94e'; type: Media.IconData.Light }
		// science: Media.IconData { path: '\ue94f'; type: Media.IconData.Light }
		// search: Media.IconData { path: '\ue950'; type: Media.IconData.Light }
		// security: Media.IconData { path: '\ue951'; type: Media.IconData.Light }
		// sell: Media.IconData { path: '\ue952'; type: Media.IconData.Light }
		// send: Media.IconData { path: '\ue953'; type: Media.IconData.Light }
		settings: Media.IconData { path: '\ue954'; type: Media.IconData.Light }
		// share: Media.IconData { path: '\ue955'; type: Media.IconData.Light }
		// shoppingBag: Media.IconData { path: '\ue956'; type: Media.IconData.Light }
		// shoppingCart: Media.IconData { path: '\ue957'; type: Media.IconData.Light }
		// shuffle: Media.IconData { path: '\ue958'; type: Media.IconData.Light }
		// signalCellularAlt: Media.IconData { path: '\ue959'; type: Media.IconData.Light }
		// skipNext: Media.IconData { path: '\ue95a'; type: Media.IconData.Light }
		// skipPrevious: Media.IconData { path: '\ue95b'; type: Media.IconData.Light }
		// smartphone: Media.IconData { path: '\ue95c'; type: Media.IconData.Light }
		// sort: Media.IconData { path: '\ue95d'; type: Media.IconData.Light }
		// sportsEsports: Media.IconData { path: '\ue95e'; type: Media.IconData.Light }
		// sportsSoccer: Media.IconData { path: '\ue95f'; type: Media.IconData.Light }
		// stadiaController: Media.IconData { path: '\ue960'; type: Media.IconData.Light }
		// star: Media.IconData { path: '\ue961'; type: Media.IconData.Light }
		// stop: Media.IconData { path: '\ue962'; type: Media.IconData.Light }
		// stopCircle: Media.IconData { path: '\ue963'; type: Media.IconData.Light }
		// storage: Media.IconData { path: '\ue964'; type: Media.IconData.Light }
		// store: Media.IconData { path: '\ue965'; type: Media.IconData.Light }
		// storefront: Media.IconData { path: '\ue966'; type: Media.IconData.Light }
		// subscriptions: Media.IconData { path: '\ue967'; type: Media.IconData.Light }
		// sync: Media.IconData { path: '\ue968'; type: Media.IconData.Light }
		// taskAlt: Media.IconData { path: '\ue969'; type: Media.IconData.Light }
		// theaters: Media.IconData { path: '\ue96a'; type: Media.IconData.Light }
		// thumbUp: Media.IconData { path: '\ue96b'; type: Media.IconData.Light }
		// timeline: Media.IconData { path: '\ue96c'; type: Media.IconData.Light }
		// timer: Media.IconData { path: '\ue96d'; type: Media.IconData.Light }
		// touchApp: Media.IconData { path: '\ue96e'; type: Media.IconData.Light }
		// trendingDown: Media.IconData { path: '\ue96f'; type: Media.IconData.Light }
		// trendingUp: Media.IconData { path: '\ue970'; type: Media.IconData.Light }
		// tune: Media.IconData { path: '\ue971'; type: Media.IconData.Light }
		// undo: Media.IconData { path: '\ue972'; type: Media.IconData.Light }
		// update: Media.IconData { path: '\ue973'; type: Media.IconData.Light }
		// uploadFile: Media.IconData { path: '\ue974'; type: Media.IconData.Light }
		// usb: Media.IconData { path: '\ue975'; type: Media.IconData.Light }
		// verified: Media.IconData { path: '\ue976'; type: Media.IconData.Light }
		// verifiedUser: Media.IconData { path: '\ue977'; type: Media.IconData.Light }
		// videoLibrary: Media.IconData { path: '\ue978'; type: Media.IconData.Light }
		// videocam: Media.IconData { path: '\ue979'; type: Media.IconData.Light }
		// visibility: Media.IconData { path: '\ue97a'; type: Media.IconData.Light }
		// visibilityOff: Media.IconData { path: '\ue97b'; type: Media.IconData.Light }
		// volumeOff: Media.IconData { path: '\ue97c'; type: Media.IconData.Light }
		// volumeUp: Media.IconData { path: '\ue97d'; type: Media.IconData.Light }
		// wallet: Media.IconData { path: '\ue97e'; type: Media.IconData.Light }
		// wallpaper: Media.IconData { path: '\ue97f'; type: Media.IconData.Light }
		// warning: Media.IconData { path: '\ue980'; type: Media.IconData.Light }
		// wbSunny: Media.IconData { path: '\ue981'; type: Media.IconData.Light }
		// whereToVote: Media.IconData { path: '\ue982'; type: Media.IconData.Light }
		// widgets: Media.IconData { path: '\ue983'; type: Media.IconData.Light }
		// wifi: Media.IconData { path: '\ue984'; type: Media.IconData.Light }
		// wifiOff: Media.IconData { path: '\ue985'; type: Media.IconData.Light }
		// work: Media.IconData { path: '\ue986'; type: Media.IconData.Light }
		// accountBalance: Media.IconData { path: '\ue987'; type: Media.IconData.Light }
		// accountBox: Media.IconData { path: '\ue988'; type: Media.IconData.Light }
		// accountCircle: Media.IconData { path: '\ue989'; type: Media.IconData.Light }
		// adb: Media.IconData { path: '\ue98a'; type: Media.IconData.Light }
		// add: Media.IconData { path: '\ue98b'; type: Media.IconData.Light }
		// addAPhoto: Media.IconData { path: '\ue98c'; type: Media.IconData.Light }
		// addBox: Media.IconData { path: '\ue98d'; type: Media.IconData.Light }
		// addBusiness: Media.IconData { path: '\ue98e'; type: Media.IconData.Light }
		// addCard: Media.IconData { path: '\ue98f'; type: Media.IconData.Light }
		// addCircle: Media.IconData { path: '\ue990'; type: Media.IconData.Light }
		// addPhotoAlternate: Media.IconData { path: '\ue991'; type: Media.IconData.Light }
		// addShoppingCart: Media.IconData { path: '\ue992'; type: Media.IconData.Light }
		// air: Media.IconData { path: '\ue993'; type: Media.IconData.Light }
		// alarm: Media.IconData { path: '\ue994'; type: Media.IconData.Light }
		// analytics: Media.IconData { path: '\ue995'; type: Media.IconData.Light }
		// android: Media.IconData { path: '\ue996'; type: Media.IconData.Light }
		// apps: Media.IconData { path: '\ue997'; type: Media.IconData.Light }
		// arrowBack: Media.IconData { path: '\ue998'; type: Media.IconData.Light }
		// arrowDownward: Media.IconData { path: '\ue999'; type: Media.IconData.Light }
		// arrowDropDown: Media.IconData { path: '\ue99a'; type: Media.IconData.Light }
		// arrowDropUp: Media.IconData { path: '\ue99b'; type: Media.IconData.Light }
		// arrowForward: Media.IconData { path: '\ue99c'; type: Media.IconData.Light }
		// arrowRight: Media.IconData { path: '\ue99d'; type: Media.IconData.Light }
		// atr: Media.IconData { path: '\ue99e'; type: Media.IconData.Light }
		// attachMoney: Media.IconData { path: '\ue99f'; type: Media.IconData.Light }
		// autorenew: Media.IconData { path: '\ue9a0'; type: Media.IconData.Light }
		// backspace: Media.IconData { path: '\ue9a1'; type: Media.IconData.Light }
		// badge: Media.IconData { path: '\ue9a2'; type: Media.IconData.Light }
		// barChart: Media.IconData { path: '\ue9a3'; type: Media.IconData.Light }
		// barcodeScanner: Media.IconData { path: '\ue9a4'; type: Media.IconData.Light }
		// batteryChargingFull: Media.IconData { path: '\ue9a5'; type: Media.IconData.Light }
		// batteryFull: Media.IconData { path: '\ue9a6'; type: Media.IconData.Light }
		// batteryFullAlt: Media.IconData { path: '\ue9a7'; type: Media.IconData.Light }
		// bluetooth: Media.IconData { path: '\ue9a8'; type: Media.IconData.Light }
		// bookmark: Media.IconData { path: '\ue9a9'; type: Media.IconData.Light }
		// brush: Media.IconData { path: '\ue9aa'; type: Media.IconData.Light }
		// build: Media.IconData { path: '\ue9ab'; type: Media.IconData.Light }
		// cable: Media.IconData { path: '\ue9ac'; type: Media.IconData.Light }
		// cake: Media.IconData { path: '\ue9ad'; type: Media.IconData.Light }
		// calculate: Media.IconData { path: '\ue9ae'; type: Media.IconData.Light }
		// calendarMonth: Media.IconData { path: '\ue9af'; type: Media.IconData.Light }
		// calendarToday: Media.IconData { path: '\ue9b0'; type: Media.IconData.Light }
		// call: Media.IconData { path: '\ue9b1'; type: Media.IconData.Light }
		// camera: Media.IconData { path: '\ue9b2'; type: Media.IconData.Light }
		// campaign: Media.IconData { path: '\ue9b3'; type: Media.IconData.Light }
		// cancel: Media.IconData { path: '\ue9b4'; type: Media.IconData.Light }
		// cast: Media.IconData { path: '\ue9b5'; type: Media.IconData.Light }
		// category: Media.IconData { path: '\ue9b6'; type: Media.IconData.Light }
		// celebration: Media.IconData { path: '\ue9b7'; type: Media.IconData.Light }
		// chat: Media.IconData { path: '\ue9b8'; type: Media.IconData.Light }
		// chatBubble: Media.IconData { path: '\ue9b9'; type: Media.IconData.Light }
		// check: Media.IconData { path: '\ue9ba'; type: Media.IconData.Light }
		// checkBox: Media.IconData { path: '\ue9bb'; type: Media.IconData.Light }
		// checkBoxOutlineBlank: Media.IconData { path: '\ue9bc'; type: Media.IconData.Light }
		// checkCircle: Media.IconData { path: '\ue9bd'; type: Media.IconData.Light }
		// chevronLeft: Media.IconData { path: '\ue9be'; type: Media.IconData.Light }
		// chevronRight: Media.IconData { path: '\ue9bf'; type: Media.IconData.Light }
		// circle: Media.IconData { path: '\ue9c0'; type: Media.IconData.Light }
		// close: Media.IconData { path: '\ue9c1'; type: Media.IconData.Light }
		// code: Media.IconData { path: '\ue9c2'; type: Media.IconData.Light }
		// computer: Media.IconData { path: '\ue9c3'; type: Media.IconData.Light }
		// construction: Media.IconData { path: '\ue9c4'; type: Media.IconData.Light }
		// contactSupport: Media.IconData { path: '\ue9c5'; type: Media.IconData.Light }
		// contentCopy: Media.IconData { path: '\ue9c6'; type: Media.IconData.Light }
		// creditCard: Media.IconData { path: '\ue9c7'; type: Media.IconData.Light }
		// cropFree: Media.IconData { path: '\ue9c8'; type: Media.IconData.Light }
		// currencyBitcoin: Media.IconData { path: '\ue9c9'; type: Media.IconData.Light }
		// darkMode: Media.IconData { path: '\ue9ca'; type: Media.IconData.Light }
		// dashboard: Media.IconData { path: '\ue9cb'; type: Media.IconData.Light }
		// database: Media.IconData { path: '\ue9cc'; type: Media.IconData.Light }
		// deleteElement: Media.IconData { path: '\ue9cd'; type: Media.IconData.Light }
		// deleteForever: Media.IconData { path: '\ue9ce'; type: Media.IconData.Light }
		// description: Media.IconData { path: '\ue9cf'; type: Media.IconData.Light }
		// devices: Media.IconData { path: '\ue9d0'; type: Media.IconData.Light }
		// directionsCar: Media.IconData { path: '\ue9d1'; type: Media.IconData.Light }
		// domain: Media.IconData { path: '\ue9d2'; type: Media.IconData.Light }
		// doneAll: Media.IconData { path: '\ue9d3'; type: Media.IconData.Light }
		// download: Media.IconData { path: '\ue9d4'; type: Media.IconData.Light }
		// downloadForOffline: Media.IconData { path: '\ue9d5'; type: Media.IconData.Light }
		// draw: Media.IconData { path: '\ue9d6'; type: Media.IconData.Light }
		// eco: Media.IconData { path: '\ue9d7'; type: Media.IconData.Light }
		// edit: Media.IconData { path: '\ue9d8'; type: Media.IconData.Light }
		// editNote: Media.IconData { path: '\ue9d9'; type: Media.IconData.Light }
		// electricBolt: Media.IconData { path: '\ue9da'; type: Media.IconData.Light }
		// emojiObjects: Media.IconData { path: '\ue9db'; type: Media.IconData.Light }
		// engineering: Media.IconData { path: '\ue9dc'; type: Media.IconData.Light }
		// error: Media.IconData { path: '\ue9dd'; type: Media.IconData.Light }
		// euro: Media.IconData { path: '\ue9de'; type: Media.IconData.Light }
		// event: Media.IconData { path: '\ue9df'; type: Media.IconData.Light }
		// explore: Media.IconData { path: '\ue9e0'; type: Media.IconData.Light }
		// extension: Media.IconData { path: '\ue9e1'; type: Media.IconData.Light }
		// familiarFaceAndZone: Media.IconData { path: '\ue9e2'; type: Media.IconData.Light }
		// fastForward: Media.IconData { path: '\ue9e3'; type: Media.IconData.Light }
		// fastRewind: Media.IconData { path: '\ue9e4'; type: Media.IconData.Light }
		// favorite: Media.IconData { path: '\ue9e5'; type: Media.IconData.Light }
		// fileCopy: Media.IconData { path: '\ue9e6'; type: Media.IconData.Light }
		// filterAlt: Media.IconData { path: '\ue9e7'; type: Media.IconData.Light }
		// filterList: Media.IconData { path: '\ue9e8'; type: Media.IconData.Light }
		// finance: Media.IconData { path: '\ue9e9'; type: Media.IconData.Light }
		// fingerprint: Media.IconData { path: '\ue9ea'; type: Media.IconData.Light }
		// flag: Media.IconData { path: '\ue9eb'; type: Media.IconData.Light }
		// flashOn: Media.IconData { path: '\ue9ec'; type: Media.IconData.Light }
		// flashlightOn: Media.IconData { path: '\ue9ed'; type: Media.IconData.Light }
		// flight: Media.IconData { path: '\ue9ee'; type: Media.IconData.Light }
		// folder: Media.IconData { path: '\ue9ef'; type: Media.IconData.Light }
		// folderOpen: Media.IconData { path: '\ue9f0'; type: Media.IconData.Light }
		// forum: Media.IconData { path: '\ue9f1'; type: Media.IconData.Light }
		// gridOn: Media.IconData { path: '\ue9f2'; type: Media.IconData.Light }
		// gridView: Media.IconData { path: '\ue9f3'; type: Media.IconData.Light }
		// group: Media.IconData { path: '\ue9f4'; type: Media.IconData.Light }
		// groupAdd: Media.IconData { path: '\ue9f5'; type: Media.IconData.Light }
		// groups: Media.IconData { path: '\ue9f6'; type: Media.IconData.Light }
		// handyman: Media.IconData { path: '\ue9f7'; type: Media.IconData.Light }
		// headphones: Media.IconData { path: '\ue9f8'; type: Media.IconData.Light }
		// hearing: Media.IconData { path: '\ue9f9'; type: Media.IconData.Light }
		// help: Media.IconData { path: '\ue9fa'; type: Media.IconData.Light }
		// history: Media.IconData { path: '\ue9fb'; type: Media.IconData.Light }
		// home: Media.IconData { path: '\ue9fc'; type: Media.IconData.Light }
		// homePin: Media.IconData { path: '\ue9fd'; type: Media.IconData.Light }
		// image: Media.IconData { path: '\ue9fe'; type: Media.IconData.Light }
		// imagesmode: Media.IconData { path: '\ue9ff'; type: Media.IconData.Light }
		info: Media.IconData { path: '\uea00'; type: Media.IconData.Light }
		// inventory: Media.IconData { path: '\uea01'; type: Media.IconData.Light }
		// colorize: Media.IconData { path: '\uea02'; type: Media.IconData.Light }
    }

    function getAll() : list<string> {
        // let heavyList = _root.heavy.getAll();
        let lightList = _root.light.getAll();
		return lightList;
        // let combinedList = heavyList.slice();
        // for (let i = 0; i < lightList.length; i++) {
        //    if (combinedList.indexOf(lightList[i]) === -1) {
        //         combinedList.push(lightList[i]);
        //     }
        // }
        // return combinedList;
    }
}
